language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew --project-cache-dir .gradle -PdocDir=docs generateHTML
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
